name: CI

on:
    push:
        branches:
            - master
    pull_request:

    workflow_dispatch:

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 2

            - name: Setup volta
              uses: volta-cli/action@v3

            - name: Use dependencies cache
              id: cache-node-modules
              uses: actions/cache@v3
              env:
                  cache-name: cache-node-modules
              with:
                  path: |
                      node_modules
                      **/node_modules
                  key: node-modules-${{ hashFiles('package-lock.json') }}

            - name: Install dependencies
              if: steps.cache-node-modules.outputs.cache-hit != 'true'
              run: npm ci

            - name: Lint code
              run: npm run lint

    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 2

            - name: Setup volta
              uses: volta-cli/action@v3

            - name: Use dependencies cache
              id: cache-node-modules
              uses: actions/cache@v3
              env:
                  cache-name: cache-node-modules
              with:
                  path: |
                      node_modules
                      **/node_modules
                  key: node-modules-${{ hashFiles('package-lock.json') }}

            - name: Install dependencies
              if: steps.cache-node-modules.outputs.cache-hit != 'true'
              run: npm ci

            - name: Typecheck
              run: npm run typecheck

            - name: Test code
              run: npm run test
