import { createGlobalTheme } from '@vanilla-extract/css'

import type { TStarbaseUIThemeVars } from './createStarbaseThemeVars'
import { TStarbaseUIThemeTokens } from './types'

const createStarbaseTheme = (themeVars: TStarbaseUIThemeVars, themeTokens: TStarbaseUIThemeTokens) => {
    const { colors, ...restTokens } = themeTokens

    createGlobalTheme(':root', themeVars, {
        ...restTokens,
        colors: {
            ...colors,
            appBackground: themeVars.colors.neutral100,
            surfaceBackground: themeVars.colors.neutral50,
            separatorColor: themeVars.colors.neutral200,
            //solid
            neutralSolidColor: '#fff',
            neutralSolidColorDisabled: '#fff',
            neutralSolidBgColor: themeVars.colors.neutral500,
            neutralSolidBgColorHover: themeVars.colors.neutral600,
            neutralSolidBgColorActive: themeVars.colors.neutral700,
            neutralSolidBgColorDisabled: themeVars.colors.neutral200,
            //soft
            neutralSoftColor: themeVars.colors.neutral600,
            neutralSoftColorDisabled: themeVars.colors.neutral300,
            neutralSoftBgColor: themeVars.colors.neutral100,
            neutralSoftBgColorHover: themeVars.colors.neutral200,
            neutralSoftBgColorActive: themeVars.colors.neutral300,
            neutralSoftBgColorDisabled: themeVars.colors.neutral50,
            //outlined
            neutralOutlinedColor: themeVars.colors.neutral500,
            neutralOutlinedColorDisabled: themeVars.colors.neutral100,
            // neutralOutlinedBgColor: 'transparent',
            neutralOutlinedBgColorHover: themeVars.colors.neutral100,
            neutralOutlinedBgColorActive: themeVars.colors.neutral200,
            neutralOutlinedBorderColor: themeVars.colors.neutral200,
            neutralOutlinedBorderColorHover: themeVars.colors.neutral300,
            neutralOutlinedBorderColorActive: themeVars.colors.neutral400,
            neutralOutlinedBorderColorDisabled: themeVars.colors.neutral100,
            //subtle
            neutralSubtleColor: themeVars.colors.neutral600,
            neutralSubtleColorDisabled: themeVars.colors.neutral200,
            neutralSubtleBgColorHover: themeVars.colors.neutral100,
            neutralSubtleBgColorActive: themeVars.colors.neutral200,
            primarySolidColor: '#fff',
            primarySolidColorDisabled: '#fff',
            primarySolidBgColor: themeVars.colors.primary500,
            primarySolidBgColorHover: themeVars.colors.primary600,
            primarySolidBgColorActive: themeVars.colors.primary700,
            primarySolidBgColorDisabled: themeVars.colors.primary200,
            //soft
            primarySoftColor: themeVars.colors.primary600,
            primarySoftColorDisabled: themeVars.colors.primary300,
            primarySoftBgColor: themeVars.colors.primary100,
            primarySoftBgColorHover: themeVars.colors.primary200,
            primarySoftBgColorActive: themeVars.colors.primary300,
            primarySoftBgColorDisabled: themeVars.colors.primary50,
            //outlined
            primaryOutlinedColor: themeVars.colors.primary500,
            primaryOutlinedColorDisabled: themeVars.colors.primary100,
            primaryOutlinedBgColorHover: themeVars.colors.primary100,
            primaryOutlinedBgColorActive: themeVars.colors.primary200,
            primaryOutlinedBorderColor: themeVars.colors.primary200,
            primaryOutlinedBorderColorHover: themeVars.colors.primary300,
            primaryOutlinedBorderColorActive: themeVars.colors.primary400,
            primaryOutlinedBorderColorDisabled: themeVars.colors.primary100,
            //subtle
            primarySubtleColor: themeVars.colors.primary600,
            primarySubtleColorDisabled: themeVars.colors.primary200,
            primarySubtleBgColorHover: themeVars.colors.primary100,
            primarySubtleBgColorActive: themeVars.colors.primary200,
            secondarySolidColor: '#fff',
            secondarySolidColorDisabled: '#fff',
            secondarySolidBgColor: themeVars.colors.secondary500,
            secondarySolidBgColorHover: themeVars.colors.secondary600,
            secondarySolidBgColorActive: themeVars.colors.secondary700,
            secondarySolidBgColorDisabled: themeVars.colors.secondary200,
            //soft
            secondarySoftColor: themeVars.colors.secondary600,
            secondarySoftColorDisabled: themeVars.colors.secondary300,
            secondarySoftBgColor: themeVars.colors.secondary100,
            secondarySoftBgColorHover: themeVars.colors.secondary200,
            secondarySoftBgColorActive: themeVars.colors.secondary300,
            secondarySoftBgColorDisabled: themeVars.colors.secondary50,
            //outlined
            secondaryOutlinedColor: themeVars.colors.secondary500,
            secondaryOutlinedColorDisabled: themeVars.colors.secondary100,
            secondaryOutlinedBgColorHover: themeVars.colors.secondary100,
            secondaryOutlinedBgColorActive: themeVars.colors.secondary200,
            secondaryOutlinedBorderColor: themeVars.colors.secondary200,
            secondaryOutlinedBorderColorHover: themeVars.colors.secondary300,
            secondaryOutlinedBorderColorActive: themeVars.colors.secondary400,
            secondaryOutlinedBorderColorDisabled: themeVars.colors.secondary100,
            //subtle
            secondarySubtleColor: themeVars.colors.secondary600,
            secondarySubtleColorDisabled: themeVars.colors.secondary200,
            secondarySubtleBgColorHover: themeVars.colors.secondary100,
            secondarySubtleBgColorActive: themeVars.colors.secondary200,
            successSolidColor: '#fff',
            successSolidColorDisabled: '#fff',
            successSolidBgColor: themeVars.colors.success500,
            successSolidBgColorHover: themeVars.colors.success600,
            successSolidBgColorActive: themeVars.colors.success700,
            successSolidBgColorDisabled: themeVars.colors.success200,
            //soft
            successSoftColor: themeVars.colors.success600,
            successSoftColorDisabled: themeVars.colors.success300,
            successSoftBgColor: themeVars.colors.success100,
            successSoftBgColorHover: themeVars.colors.success200,
            successSoftBgColorActive: themeVars.colors.success300,
            successSoftBgColorDisabled: themeVars.colors.success50,
            //outlined
            successOutlinedColor: themeVars.colors.success500,
            successOutlinedColorDisabled: themeVars.colors.success100,
            successOutlinedBgColorHover: themeVars.colors.success100,
            successOutlinedBgColorActive: themeVars.colors.success200,
            successOutlinedBorderColor: themeVars.colors.success200,
            successOutlinedBorderColorHover: themeVars.colors.success300,
            successOutlinedBorderColorActive: themeVars.colors.success400,
            successOutlinedBorderColorDisabled: themeVars.colors.success100,
            //subtle
            successSubtleColor: themeVars.colors.success600,
            successSubtleColorDisabled: themeVars.colors.success200,
            successSubtleBgColorHover: themeVars.colors.success100,
            successSubtleBgColorActive: themeVars.colors.success200,
            dangerSolidColor: '#fff',
            dangerSolidColorDisabled: '#fff',
            dangerSolidBgColor: themeVars.colors.danger500,
            dangerSolidBgColorHover: themeVars.colors.danger600,
            dangerSolidBgColorActive: themeVars.colors.danger700,
            dangerSolidBgColorDisabled: themeVars.colors.danger200,
            //soft
            dangerSoftColor: themeVars.colors.danger600,
            dangerSoftColorDisabled: themeVars.colors.danger300,
            dangerSoftBgColor: themeVars.colors.danger100,
            dangerSoftBgColorHover: themeVars.colors.danger200,
            dangerSoftBgColorActive: themeVars.colors.danger300,
            dangerSoftBgColorDisabled: themeVars.colors.danger50,
            //outlined
            dangerOutlinedColor: themeVars.colors.danger500,
            dangerOutlinedColorDisabled: themeVars.colors.danger100,
            dangerOutlinedBgColorHover: themeVars.colors.danger100,
            dangerOutlinedBgColorActive: themeVars.colors.danger200,
            dangerOutlinedBorderColor: themeVars.colors.danger200,
            dangerOutlinedBorderColorHover: themeVars.colors.danger300,
            dangerOutlinedBorderColorActive: themeVars.colors.danger400,
            dangerOutlinedBorderColorDisabled: themeVars.colors.danger100,
            //subtle
            dangerSubtleColor: themeVars.colors.danger600,
            dangerSubtleColorDisabled: themeVars.colors.danger200,
            dangerSubtleBgColorHover: themeVars.colors.danger100,
            dangerSubtleBgColorActive: themeVars.colors.danger200,
            warningSolidColor: '#fff',
            warningSolidColorDisabled: '#fff',
            warningSolidBgColor: themeVars.colors.warning500,
            warningSolidBgColorHover: themeVars.colors.warning600,
            warningSolidBgColorActive: themeVars.colors.warning700,
            warningSolidBgColorDisabled: themeVars.colors.warning200,
            //soft
            warningSoftColor: themeVars.colors.warning600,
            warningSoftColorDisabled: themeVars.colors.warning300,
            warningSoftBgColor: themeVars.colors.warning100,
            warningSoftBgColorHover: themeVars.colors.warning200,
            warningSoftBgColorActive: themeVars.colors.warning300,
            warningSoftBgColorDisabled: themeVars.colors.warning50,
            //outlined
            warningOutlinedColor: themeVars.colors.warning500,
            warningOutlinedColorDisabled: themeVars.colors.warning100,
            warningOutlinedBgColorHover: themeVars.colors.warning100,
            warningOutlinedBgColorActive: themeVars.colors.warning200,
            warningOutlinedBorderColor: themeVars.colors.warning200,
            warningOutlinedBorderColorHover: themeVars.colors.warning300,
            warningOutlinedBorderColorActive: themeVars.colors.warning400,
            warningOutlinedBorderColorDisabled: themeVars.colors.warning100,
            //subtle
            warningSubtleColor: themeVars.colors.warning600,
            warningSubtleColorDisabled: themeVars.colors.warning200,
            warningSubtleBgColorHover: themeVars.colors.warning100,
            warningSubtleBgColorActive: themeVars.colors.warning200,
            infoSolidColor: '#fff',
            infoSolidColorDisabled: '#fff',
            infoSolidBgColor: themeVars.colors.info500,
            infoSolidBgColorHover: themeVars.colors.info600,
            infoSolidBgColorActive: themeVars.colors.info700,
            infoSolidBgColorDisabled: themeVars.colors.info200,
            //soft
            infoSoftColor: themeVars.colors.info600,
            infoSoftColorDisabled: themeVars.colors.info300,
            infoSoftBgColor: themeVars.colors.info100,
            infoSoftBgColorHover: themeVars.colors.info200,
            infoSoftBgColorActive: themeVars.colors.info300,
            infoSoftBgColorDisabled: themeVars.colors.info50,
            //outlined
            infoOutlinedColor: themeVars.colors.info500,
            infoOutlinedColorDisabled: themeVars.colors.info100,
            infoOutlinedBgColorHover: themeVars.colors.info100,
            infoOutlinedBgColorActive: themeVars.colors.info200,
            infoOutlinedBorderColor: themeVars.colors.info200,
            infoOutlinedBorderColorHover: themeVars.colors.info300,
            infoOutlinedBorderColorActive: themeVars.colors.info400,
            infoOutlinedBorderColorDisabled: themeVars.colors.info100,
            //subtle
            infoSubtleColor: themeVars.colors.info600,
            infoSubtleColorDisabled: themeVars.colors.info200,
            infoSubtleBgColorHover: themeVars.colors.info100,
            infoSubtleBgColorActive: themeVars.colors.info200
        }
    })
}

export { createStarbaseTheme }
