name: CI

on:
    push:
        branches:
            - master
    pull_request:

    workflow_dispatch:

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 2
            - name: Setup volta
              uses: volta-cli/action@v3
            - name: Install dependencies
              run: npm ci
            - name: Lint code
              run: npm run lint
            - name: Typecheck
              run: npm run typecheck

    test:
        name: Test
        runs-on: ubuntu-latest
        needs: Lint
        steps:
           - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 2
            - name: Setup volta
              uses: volta-cli/action@v3
            - name: Install dependencies
              run: npm ci
            - name: Test code
              run: npm run test
